name: Laravel CI (PostgreSQL)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  # ⬇️ Ajusta esto según dónde viva tu app
  WORKDIR: "."   # usa "." si artisan está en la raíz

jobs:
  tests:
    name: PHP ${{ matrix.php }} • PostgreSQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: laravel_test
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U laravel -d laravel_test"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      APP_ENV: testing
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: laravel_test
      DB_USERNAME: laravel
      DB_PASSWORD: secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo_pgsql, bcmath, xml, curl, fileinfo, tokenizer, ctype, dom, json, zip
          coverage: xdebug
          tools: composer:v2

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Show repo & project dir (debug)
        run: |
          echo "::group::Repo root"; ls -la; echo "::endgroup::"
          echo "::group::Project ($WORKDIR)"; ls -la "$WORKDIR"; echo "::endgroup::"

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            ${{ env.WORKDIR }}/vendor
          key: composer-${{ runner.os }}-${{ hashFiles(format('{0}/composer.lock', env.WORKDIR)) }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install PHP deps
        working-directory: ${{ env.WORKDIR }}
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Copy .env (if missing)
        working-directory: ${{ env.WORKDIR }}
        run: if [ ! -f .env ]; then cp .env.example .env; fi

      - name: Generate key
        working-directory: ${{ env.WORKDIR }}
        run: php artisan key:generate --force

      - name: Set writable folders
        working-directory: ${{ env.WORKDIR }}
        run: chmod -R 777 storage bootstrap/cache || true

      - name: Clear caches (defensivo)
        working-directory: ${{ env.WORKDIR }}
        run: |
          php artisan config:clear || true
          php artisan cache:clear || true
          php artisan route:clear || true
          php artisan view:clear || true

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U "$DB_USERNAME" -d "$DB_DATABASE" && break
            echo "DB not ready yet... ($i)"; sleep 2
          done

      - name: Run migrations & seeders
        working-directory: ${{ env.WORKDIR }}
        run: php artisan migrate --seed --no-interaction

      - name: Migrate fresh + seed (sanity)
        working-directory: ${{ env.WORKDIR }}
        run: php artisan migrate:fresh --seed --no-interaction

      - name: Composer audit
        working-directory: ${{ env.WORKDIR }}
        continue-on-error: true
        run: composer audit --no-interaction

      - name: Laravel Pint (warning-only)
        working-directory: ${{ env.WORKDIR }}
        run: |
          if [ -f vendor/bin/pint ]; then
            vendor/bin/pint --test || echo "Pint encontró issues (no bloquea el CI)."
          else
            echo "Pint no instalado"
          fi

      - name: PHPStan (opcional)
        working-directory: ${{ env.WORKDIR }}
        continue-on-error: true
        run: |
          if [ -f vendor/bin/phpstan ]; then vendor/bin/phpstan analyse --no-progress --memory-limit=1G; else echo "PHPStan no instalado"; fi

      - name: Node setup (si hay package.json)
        if: hashFiles(format('{0}/package.json', env.WORKDIR)) != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node
        if: hashFiles(format('{0}/package.json', env.WORKDIR)) != ''
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ env.WORKDIR }}/node_modules
          key: node-${{ runner.os }}-${{ hashFiles(format('{0}/package-lock.json', env.WORKDIR), format('{0}/pnpm-lock.yaml', env.WORKDIR), format('{0}/yarn.lock', env.WORKDIR)) }}
          restore-keys: |
            node-${{ runner.os }}-

      - name: Build Frontend (opcional)
        if: hashFiles(format('{0}/package.json', env.WORKDIR)) != ''
        working-directory: ${{ env.WORKDIR }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          npx vite build || echo "Vite build opcional"

      - name: Run tests (si existen)
        working-directory: ${{ env.WORKDIR }}
        run: |
          if [ -f vendor/bin/pest ]; then
            XDEBUG_MODE=coverage vendor/bin/pest --colors=always --coverage --coverage-html coverage
          elif [ -f vendor/bin/phpunit ]; then
            XDEBUG_MODE=coverage vendor/bin/phpunit --colors=always --coverage-text --coverage-html coverage
          else
            echo "No hay tests (Pest/PHPUnit)."
          fi

      - name: Upload coverage artifact (solo si existe)
        if: ${{ hashFiles(format('{0}/coverage/index.html', env.WORKDIR)) != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.php }}
          path: ${{ env.WORKDIR }}/coverage
